import json
import subprocess
import tempfile
import unittest
from pathlib import Path


SCRIPT = Path(__file__).resolve().parents[1] / "libexec" / "docking-universal-ccd-audit.py"


class CcdAuditTests(unittest.TestCase):
    def test_modres_ccd_generation_and_retention_are_recorded(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            pdb = root / "input.pdb"
            pdbqt = root / "receptor.pdbqt"
            log = root / "meeko.log"
            output_json = root / "audit.json"
            output_tsv = root / "audit.tsv"
            pdb.write_text(
                "MODRES 1ABC CSO A   67  CYS  S-HYDROXYCYSTEINE\n"
                "ATOM      1  CA  CSO A  67       0.000   0.000   0.000  1.00  0.00           C\n"
            )
            pdbqt.write_text(
                "ATOM      1  CA  CSO A  67       0.000   0.000   0.000  1.00  0.00     0.000 C \n"
            )
            log.write_text(
                'Trying to resolve unknown residues by building chemical templates...\n'
                '"ambiguous": {\n  "CSO": ["CSO"]\n}\n'
            )
            subprocess.run([
                str(SCRIPT), str(pdb), str(pdbqt), str(log), "strict_meeko",
                str(output_json), str(output_tsv),
            ], check=True, capture_output=True, text=True)
            audit = json.loads(output_json.read_text())
            self.assertEqual(audit["modified_polymer_residue_count"], 1)
            self.assertTrue(audit["all_retained"])
            self.assertEqual(audit["residues"][0]["standard_parent"], "CYS")
            self.assertEqual(audit["residues"][0]["resolution"], "CCD template generated by Meeko")
            self.assertIn("A:67\tCSO\tCYS", output_tsv.read_text())

    def test_no_modres_writes_empty_audit(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            paths = [root / name for name in ("input.pdb", "receptor.pdbqt", "meeko.log", "audit.json", "audit.tsv")]
            for path in paths[:3]:
                path.write_text("")
            subprocess.run([
                str(SCRIPT), str(paths[0]), str(paths[1]), str(paths[2]), "strict_meeko",
                str(paths[3]), str(paths[4]),
            ], check=True, capture_output=True, text=True)
            audit = json.loads(paths[3].read_text())
            self.assertEqual(audit["modified_polymer_residue_count"], 0)
            self.assertTrue(audit["all_retained"])


if __name__ == "__main__":
    unittest.main()
