#!/usr/bin/env python3
"""Record how MODRES-declared polymer modifications reached receptor PDBQT."""

import argparse
import json
import re
from pathlib import Path


def modres_records(path):
    records = []
    seen = set()
    for line in Path(path).read_text(errors="replace").splitlines():
        if not line.startswith("MODRES"):
            continue
        component = line[12:15].strip()
        chain = line[16:17].strip()
        residue_number = line[18:22].strip()
        insertion_code = line[22:23].strip()
        standard_parent = line[24:27].strip()
        description = line[29:70].strip()
        residue_id = f"{chain}:{residue_number}{insertion_code}"
        key = (residue_id, component)
        if key in seen:
            continue
        seen.add(key)
        records.append({
            "residue": residue_id,
            "component": component,
            "standard_parent": standard_parent,
            "description": description,
        })
    return records


def retained_components(path):
    retained = set()
    path = Path(path)
    if not path.is_file():
        return retained
    for line in path.read_text(errors="replace").splitlines():
        if not line.startswith(("ATOM  ", "HETATM")):
            continue
        component = line[17:20].strip()
        chain = line[21:22].strip()
        residue_number = line[22:26].strip()
        insertion_code = line[26:27].strip()
        retained.add((f"{chain}:{residue_number}{insertion_code}", component))
    return retained


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input_pdb")
    parser.add_argument("receptor_pdbqt")
    parser.add_argument("backend_log")
    parser.add_argument("route")
    parser.add_argument("json_output")
    parser.add_argument("tsv_output")
    args = parser.parse_args()

    records = modres_records(args.input_pdb)
    retained = retained_components(args.receptor_pdbqt)
    log_path = Path(args.backend_log)
    log = log_path.read_text(errors="replace") if log_path.is_file() else ""
    generated_components = set(re.findall(
        r'"ambiguous"\s*:\s*\{\s*"([^"\n]+)"', log
    ))

    for record in records:
        present = (record["residue"], record["component"]) in retained
        if not present:
            resolution = "not retained in final receptor"
        elif record["component"] in generated_components:
            resolution = "CCD template generated by Meeko"
        elif args.route == "pdbfixer_then_strict_meeko":
            resolution = "retained after PDBFixer and strict Meeko"
        else:
            resolution = "resolved by an available Meeko template"
        record.update({
            "retained_in_receptor_pdbqt": present,
            "resolution": resolution,
            "evidence": str(log_path),
        })

    audit = {
        "schema_name": "docking-universal-ccd-modification-audit",
        "schema_version": 1,
        "input_pdb": str(Path(args.input_pdb).resolve()),
        "receptor_pdbqt": str(Path(args.receptor_pdbqt).resolve()),
        "preparation_route": args.route,
        "modified_polymer_residue_count": len(records),
        "all_retained": all(item["retained_in_receptor_pdbqt"] for item in records),
        "residues": records,
        "scope_note": "MODRES/CCD audit only; covalent adduct links, glycans, and metal coordination require separate review.",
    }
    Path(args.json_output).write_text(json.dumps(audit, indent=2) + "\n")
    with Path(args.tsv_output).open("w") as handle:
        handle.write("residue\tcomponent\tstandard_parent\tdescription\tresolution\tretained\tevidence\n")
        for item in records:
            values = (
                item["residue"], item["component"], item["standard_parent"],
                item["description"], item["resolution"],
                "yes" if item["retained_in_receptor_pdbqt"] else "no", item["evidence"],
            )
            handle.write("\t".join(value.replace("\t", " ") for value in values) + "\n")
    print(json.dumps(audit))


if __name__ == "__main__":
    main()
